#!/bin/bash

# Copyright (C) 2015 by Wilson E. Alvarez <wilson.e.alvarez1@gmail.com>
# Software has been released under the MIT License.
# To view the full license, please visit the following link:
# 	https://raw.githubusercontent.com/Arkranur/bash-scripts/master/LICENSE

printf_permission () {
case $1 in
        0) printf "no permissions\n" ;;
        1) printf "execute only permission\n" ;;
        2) printf "write only permission\n" ;;
        3) printf "write and execute permissions\n" ;;
        4) printf "read only permission\n" ;;
        5) printf "read and execute permissions\n" ;;
        6) printf "read and write permissions\n" ;;
        7) printf "read, write and execute permissions\n" ;;
esac

}

#Obtaining user's umask to calculate file and folder permissions
user_umask=`umask`

#Calculating File Permissions using octal digits
first_digit=$((6&~${user_umask:1:1}))
second_digit=$((6&~${user_umask:2:1}))
third_digit=$((6&~${user_umask:3:1}))

printf "\n"
printf "In a newly create file...\n"
printf "Owner has `printf_permission $first_digit`\n"
printf "Group has `printf_permission $second_digit`\n"
printf "Others have `printf_permission $third_digit`\n"
printf "Permissions in octal are: $first_digit$second_digit$third_digit\n"

#Calculating Folder Permissions using octal digits
first_digit=$((7&~${user_umask:1:1}))
second_digit=$((7&~${user_umask:2:1}))
third_digit=$((7&~${user_umask:3:1}))

printf "\n"
printf "In a newly create folder...\n"
printf "Owner has `printf_permission $first_digit`\n"
printf "Group has `printf_permission $second_digit`\n"
printf "Others have `printf_permission $third_digit`\n"
printf "Folder Permissions in octal are: $first_digit$second_digit$third_digit\n"
printf "\n"
