#!/bin/bash

# Copyright (C) 2015 by Wilson E. Alvarez <wilson.e.alvarez1@gmail.com>
# Software has been released under the MIT License.
# To view the full license, please visit the following link:
# 	https://raw.githubusercontent.com/Arkranur/bash-scripts/master/LICENSE

printf "CIDR\t\tSubnet Mask\n"

if [[ -n $1 ]]; then
	i=$1
else
	i=16
fi

for i in `seq $i 32 | sort -nr`; do
first_octet=255
second_octet=255
third_octet=255
fourth_octet=255
	[[ $i -ge 24 && $i -le 32 ]] && fourth_octet=$(($fourth_octet+1-2**(32-$i)))
	[[ $i -ge 16 && $i -lt 24 ]] && fourth_octet=0 && third_octet=$(($third_octet+1-2**(24-$i)))
	[[ $i -ge 8  && $i -lt 16 ]] && fourth_octet=0 && third_octet=0 && second_octet=$(($second_octet+1-2**(16-$i)))
	[[ $i -gt 0 && $i -lt 8 ]] && fourth_octet=0 && third_octet=0 && second_octet=0 && first_octet=$(($first_octet+1-2**(8-$i)))
	printf "/$i\t\t$(($first_octet)).$(($second_octet)).$(($third_octet)).$(($fourth_octet))\n"
done
