#!/bin/bash

# Copyright (C) 2015 by Wilson E. Alvarez <wilson.e.alvarez1@gmail.com>
# Software has been released under the MIT License.
# To view the full license, please visit the following link:
# 	https://raw.githubusercontent.com/Arkranur/bash-scripts/master/LICENSE

if [[ $1 != "-r" ]]; then
  one=`printf "obase=2; 1" | bc | awk '{print "00" $0}'`
  two=`printf "obase=2; 2" | bc | awk '{print "0" $0}'`
  three=`printf "obase=2; 3" | bc | awk '{print "0" $0}'`
  four=`printf "obase=2; 4" | bc`
  five=`printf "obase=2; 5" | bc`
  six=`printf "obase=2; 6" | bc`
  seven=`printf "obase=2; 7" | bc`
  
  printf "Octal\tBinary"
  printf "1\t$one"
  printf "2\t$two"
  printf "3\t$three"
  printf "4\t$four"
  printf "5\t$five"
  printf "6\t$six"
  printf "7\t$seven"
else
  one=`printf "obase=2; 1" | bc | awk '{print "00" $0}'`
  two=`printf "obase=2; 2" | bc | awk '{print "0" $0}'`
  three=`printf "obase=2; 3" | bc | awk '{print "0" $0}'`
  four=`printf "obase=2; 4" | bc`
  five=`printf "obase=2; 5" | bc`
  six=`printf "obase=2; 6" | bc`
  seven=`printf "obase=2; 7" | bc`
  
  printf "Binary\tOctal"
  printf "$one\t1"
  printf "$two\t2"
  printf "$three\t3"
  printf "$four\t4"
  printf "$five\t5"
  printf "$six \t6"
  printf "$seven\t7"
fi
